import { afterEach, expect, it, vi } from 'vitest';
import { cleanup, render } from 'ink-testing-library';
import { FristenScreen } from '../../src/components/screens/FristenScreen.js';
const {context,save}=vi.hoisted(()=>({save:vi.fn(async(value:unknown)=>value),context:{allTermine:[{id:'t1',mandant_id:'M-2024-0002',mandant_name:'Schmidt KG',titel:'Fremde Mandantenfrist',datum:'2020-01-01',uhrzeit:null,erledigt:false,typ:'frist',prioritaet:'hoch',notiz:'Bitte prüfen',erstellt:'2020-01-01T10:00:00+01:00',quelle_notiz_id:null,ai_erkannt:false}],mandant:{id:'M-2024-0001'},focus:'content',setFocus:vi.fn(),overlayOpen:false,editorOpen:false,busy:false,height:20,width:76,setEditorOpen:vi.fn(),run:vi.fn(async(fn:()=>Promise<void>)=>{await fn();return true;}),refresh:vi.fn(async()=>undefined),setMessage:vi.fn()}}));
vi.mock('../../src/app/App.js',()=>({useErna:()=>context}));vi.mock('../../src/data/termine.js',()=>({saveTermin:save}));
afterEach(()=>{cleanup();vi.clearAllMocks();context.focus='content';});
it('zeigt globale Gruppen und erledigt die Frist des zugehörigen Mandanten',async()=>{const ui=render(<FristenScreen/>);await new Promise(resolve=>setTimeout(resolve,50));expect(ui.lastFrame()).toContain('Schmidt KG');expect(ui.lastFrame()).toContain('HEUTE (0)');ui.stdin.write(' ');await vi.waitFor(()=>expect(save).toHaveBeenCalledWith(expect.objectContaining({mandant_id:'M-2024-0002',erledigt:true})));});
it('bearbeitet mit F4 den richtigen Mandanten ohne Wechsel der aktuellen Akte',async()=>{const ui=render(<FristenScreen/>);await new Promise(resolve=>setTimeout(resolve,50));ui.stdin.write('\ue103');await vi.waitFor(()=>expect(ui.lastFrame()).toContain('TERMIN BEARBEITEN'));ui.stdin.write('\x13');await vi.waitFor(()=>expect(save).toHaveBeenCalledWith(expect.objectContaining({id:'t1',mandant_id:'M-2024-0002'})));});
it('reserviert Pfeile und Leertaste für die Navigation und öffnet F4 weiterhin',async()=>{context.focus='navigation';context.allTermine.push({...context.allTermine[0]!,id:'t2',titel:'Zweite Frist',notiz:'Andere Auswahl'});try{const ui=render(<FristenScreen/>);await new Promise(resolve=>setTimeout(resolve,50));ui.stdin.write('\x1b[B');await new Promise(resolve=>setTimeout(resolve,30));ui.stdin.write(' ');ui.stdin.write('\x1b[6~');await new Promise(resolve=>setTimeout(resolve,30));expect(ui.lastFrame()).toContain('Bitte prüfen');expect(ui.lastFrame()).not.toContain('Andere Auswahl');expect(save).not.toHaveBeenCalled();ui.stdin.write('\ue103');await vi.waitFor(()=>expect(ui.lastFrame()).toContain('TERMIN BEARBEITEN'));expect(context.setFocus).toHaveBeenCalledWith('content');ui.stdin.write('\x13');await vi.waitFor(()=>expect(save).toHaveBeenCalledWith(expect.objectContaining({id:'t1'})));}finally{context.allTermine.pop();}});
